import type { Report } from "@/lib/report";

export const SAMPLE_REPORT: Report = {
  target: "https://northline.example",
  targetType: "url",
  finalUrl: "https://northline.example",
  statusCode: 200,
  pageTitle: "Northline — treasury for product teams",
  tech: ["Next.js", "Vercel", "Stripe"],
  score: 61,
  grade: "C",
  summary:
    "Northline looks expensive and ships fast, but the edge is unfinished. Three headers are missing, the invoice PDF route is described without an org check, and the marketing page still has no share card. Fix the headers today; schedule the IDOR test before the next billing sprint.",
  inspectedAt: "2026-08-12T18:00:00.000Z",
  headerNames: ["cache-control", "content-type", "server", "x-powered-by"],
  enriched: true,
  compare: {
    previousScore: 54,
    previousGrade: "D",
    delta: 7,
    added: ["Session cookies are missing Secure / HttpOnly / SameSite"],
    resolved: ["MIME sniffing is allowed"],
  },
  headers: [
    { name: "HSTS", present: false, note: "Stay on HTTPS after the first visit." },
    { name: "CSP", present: false, note: "Contain a successful XSS." },
    { name: "Frame", present: false, note: "Stop foreign pages from framing you." },
    { name: "nosniff", present: true, note: "Do not let the browser guess a type." },
    { name: "Referrer", present: false, note: "Stop tokens leaking in the Referer." },
    { name: "Permissions", present: false, note: "Lock camera, mic, and geo if unused." },
    { name: "COOP", present: false, note: "Isolate this document from foreign popups." },
    { name: "CORP", present: false, note: "Stop other sites embedding this as a resource." },
  ],
  cookies: [
    {
      name: "nl_session",
      secure: false,
      httpOnly: false,
      sameSite: "",
      issues: ["missing Secure", "missing HttpOnly", "missing SameSite"],
    },
    {
      name: "nl_csrf",
      secure: true,
      httpOnly: false,
      sameSite: "lax",
      issues: [],
    },
  ],
  vendors: [
    { host: "js.stripe.com", kind: "script", category: "payments", sri: false, sample: "https://js.stripe.com/v3/" },
    { host: "www.googletagmanager.com", kind: "script", category: "analytics", sri: false, sample: "https://www.googletagmanager.com/gtag/js" },
    { host: "fonts.googleapis.com", kind: "style", category: "fonts", sri: true, sample: "https://fonts.googleapis.com/css2" },
  ],
  dns: [
    { id: "spf", label: "SPF", status: "found", detail: "v=spf1 include:_spf.google.com ~all" },
    { id: "dmarc", label: "DMARC", status: "missing", detail: "No _dmarc.northline.example." },
    { id: "caa", label: "CAA", status: "missing", detail: "No CAA on northline.example." },
  ],
  surface: [
    { id: "security-txt", label: "security.txt", status: "missing", detail: "Not published. Where researchers report a hole." },
    { id: "robots", label: "robots.txt", status: "found", detail: "HTTP 200. What you ask crawlers to skip." },
    { id: "sitemap", label: "sitemap.xml", status: "found", detail: "HTTP 200. The map search engines expect." },
    { id: "https-redirect", label: "HTTP → HTTPS", status: "found", detail: "HTTP 301 to https://northline.example/." },
    { id: "humans", label: "humans.txt", status: "missing", detail: "Not published. Who made this." },
    { id: "change-password", label: "change-password", status: "missing", detail: "Not published. Where password managers send people." },
  ],
  playbook: ["S-01", "S-02", "S-04", "S-03", "S-05", "P-01", "P-02", "P-03"],
  agents: [
    {
      name: "Scout",
      role: "Recon",
      note: "Public marketing origin plus a documented /api/invoices surface.",
    },
    {
      name: "Auditor",
      role: "Security",
      note: "Flagged missing CSP/HSTS and an unscoped invoice download.",
    },
    {
      name: "Editor",
      role: "Polish",
      note: "Hero is strong; the empty-state and og:image are not.",
    },
    {
      name: "Smith",
      role: "Solutions",
      note: "Header pack is ready to paste. IDOR fix is a one-line scope.",
    },
  ],
  findings: [
    {
      id: "S-01",
      kind: "security",
      severity: "high",
      title: "Invoice PDF is not scoped to the org",
      summary:
        "GET /api/invoices/:id/pdf fetches the file by id. Nothing in the handler description binds it to the session org.",
      detail:
        "This is the classic IDOR. A guessed UUID (or a leaked one from a forwarded email) downloads another company's invoice. Proof is a second session requesting the same id.",
      location: "api/invoices/[id]/pdf/route.ts",
      cwe: "CWE-639",
      owasp: "A01 Broken Access Control",
      cvss: 7.7,
      effort: "low",
      fixTitle: "Scope the query",
      fix: `const invoice = await db.invoice.findFirst({\n  where: { id, orgId: session.orgId },\n});\nif (!invoice) return new Response(null, { status: 404 });`,
    },
    {
      id: "S-02",
      kind: "security",
      severity: "high",
      title: "No Content-Security-Policy",
      summary: "A successful XSS on the app origin has no containment.",
      detail:
        "Northline loads Stripe.js. A CSP that allowlists js.stripe.com and self is enough to start. Ship report-only for a day, then enforce.",
      location: "response headers",
      cwe: "CWE-1021",
      owasp: "A05 Security Misconfiguration",
      cvss: 6.1,
      effort: "medium",
      fixTitle: "Enforce a first CSP",
      fix: "Content-Security-Policy: default-src 'self'; script-src 'self' https://js.stripe.com; frame-src https://js.stripe.com; img-src 'self' data: https:; object-src 'none'; base-uri 'self'; frame-ancestors 'none';",
    },
    {
      id: "S-03",
      kind: "security",
      severity: "medium",
      title: "HSTS is not set",
      summary: "TLS is on, but browsers are not told to stay there.",
      detail: "One header. Do it at the edge so preview and production inherit it.",
      location: "response headers",
      cwe: "CWE-319",
      owasp: "A02 Cryptographic Failures",
      cvss: 4.3,
      effort: "low",
      fixTitle: "Send HSTS",
      fix: "Strict-Transport-Security: max-age=63072000; includeSubDomains; preload",
    },
    {
      id: "S-04",
      kind: "security",
      severity: "high",
      title: "Session cookies are missing Secure / HttpOnly / SameSite",
      summary: "nl_session can be stolen from HTTP, JavaScript, or a cross-site request.",
      detail:
        "Set Secure, HttpOnly, and SameSite=Lax on the session cookie. The CSRF cookie can stay readable to JS but still needs Secure.",
      location: "Set-Cookie",
      cwe: "CWE-614",
      owasp: "A07 Auth Failures",
      effort: "low",
      fixTitle: "Lock the cookie",
      fix: "Set-Cookie: nl_session=…; Path=/; Secure; HttpOnly; SameSite=Lax; Max-Age=1209600",
    },
    {
      id: "S-05",
      kind: "security",
      severity: "medium",
      title: "No DMARC policy",
      summary: "Forged mail from northline.example has no published handling rule.",
      detail: "Start with p=none and a rua mailbox, then move to quarantine.",
      location: "_dmarc.northline.example",
      effort: "low",
      fixTitle: "Publish DMARC",
      fix: "v=DMARC1; p=none; rua=mailto:dmarc@northline.example; adkim=s; aspf=s",
    },
    {
      id: "P-01",
      kind: "polish",
      severity: "medium",
      title: "No share card image",
      summary: "Slack and X unfurl a title on a grey field.",
      detail:
        "The product is visual. A 1200×630 card with the wordmark and 'treasury for product teams' will outperform another week of copy edits.",
      location: "<head>",
      effort: "low",
      fixTitle: "Add og:image",
      fix: `<meta property="og:image" content="https://northline.example/og.jpg" />\n<meta property="og:image:width" content="1200" />\n<meta property="og:image:height" content="630" />`,
    },
    {
      id: "P-02",
      kind: "polish",
      severity: "medium",
      title: "Signed-in empty state is a blank table",
      summary: "A new workspace opens on zero rows and a disabled Export.",
      detail:
        "This is where trial users bounce. One sentence and one primary action ('Import a statement' or 'Create a cash account') belongs here, not a skeleton of a table they have not earned.",
      location: "app/cash/page.tsx",
      effort: "low",
      fixTitle: "Write the empty state",
      fix: "Headline: Your cash, in one place.\nBody: Import a statement or connect the bank you already use.\nCTA: Import statement",
    },
    {
      id: "P-03",
      kind: "polish",
      severity: "low",
      title: "Four H1s on the marketing page",
      summary: "The outline is a pile of heroes, not a document.",
      detail: "Keep 'treasury for product teams' as the H1. Demote feature band titles to H2.",
      location: "document outline",
      effort: "low",
      fixTitle: "One H1",
      fix: "One H1 in the hero. Feature titles → h2. Footer → no headings above h3.",
    },
    {
      id: "X-01",
      kind: "solution",
      severity: "info",
      title: "48-hour sequence",
      summary: "Do these in order. Recheck the brief when you are done.",
      detail:
        "Headers first (visible, cheap). Then the invoice scope (the one that can become an incident). Then the share card and empty state (the ones customers feel).",
      effort: "low",
      fixTitle: "Order of operations",
      fix: "1. Edge header pack (HSTS, CSP, nosniff, frame-ancestors)\n2. Scope invoice PDF to session.orgId + 404 test\n3. Ship og.jpg\n4. Replace the empty cash table\n5. Re-run this brief",
    },
  ],
};
